version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biblidex-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: eHmTzE45Of
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: biblidex-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: eHmTzE45Of
      POSTGRES_DB: biblidex
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
